### ISSUE TITLE
In last version 2022.7 don't work

### ISSUE THREAD

**Issue by janfajessen** [spycle/microbot_push#2]
Seems like HA python 3.10 update with missing bluepy and pybluez libraries casues microbot_push to stop working.. Hope you can fix it when you can. Thanks in advance

**Comment by spycle** [comment]
Unfortunately the microbot library I'm leveraging was not written by me and is no longer maintained. It needs a rewrite to use Bleak.

I would like to get it working again but it's going to be a bit of project as I'm going to have to teach myself. It won't be quick if I manage it I'm afraid

**Comment by jflefebvre06** [comment]
Do you think it is possible to install bluepy manually ?

**Comment by spycle** [comment]
You could try but if you are running Python 3.10 then my understanding is that it's not possible

**Comment by spycle** [comment]
Just to let you know that I'm making some good progress with the rewrite. Hope to release something in the next few weeks if all goes well.

**Comment by jflefebvre06** [comment]
Great new thanks

**Comment by spycle** [comment]
Still some work to do but I've release a (hopefully) working version

**Comment by jflefebvre06** [comment]
Hello
When I try to generate token I get this error message

"Échec d'appel du service "microbot_push.generate token". Service microbot_push.generate token does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'microbot_push.generate token'"

**Comment by jflefebvre06** [comment]
![Uploading Capture d’écran . 2022-07-25 à 21.59.53.png…]()

**Comment by spycle** [comment]
Ah sorry. Can you try 2022.07.2

**Comment by jflefebvre06** [comment]
Thanks  but not works, when I try to pair I get tis errors 

```
Logger: homeassistant.util.async_
Source: util/async_.py:157
First occurred: 19:32:23 (42 occurrences)
Last logged: 19:33:36

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for microbot_push doing blocking calls at custom_components/microbot_push/api.py, line 115: sleep(1)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for microbot_push doing blocking calls at custom_components/microbot_push/api.py, line 130: sleep(1)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for microbot_push doing blocking calls at custom_components/microbot_push/api.py, line 315: sleep(1)
```

**Comment by spycle** [comment]
Hmm, OK try 2022.07.3

**Comment by jflefebvre06** [comment]
Works fine thanks a lot !
